@startuml "Классы ПР1"
left to right direction

class Клиент{
  ФИО : string
  Паспортные_данные : string
  Дата_рождения : datatime
  Номер_банковского_счёта_карты : varchar
  Телефон : varchar
  Проверка_счёта()
  Снятие_наличных_со_счёта()
  Зачисление_наличных_на_счёт()
  Оплата_различных_счетов()
}

class Банкомат{
  Номер : varchar
  Местоположение : string
  Принадлежность_банку : string
  Преревод_запроса_в_операцию()
  Вывод_результата_запроса()

}


class Банк{
  Название : string
  ИНН : varchar
  КПП : varchar
  Отказ_в_операции()
  Идентификация_счёта()
  Индентификация_банкомата()
  Проверка_возможности_операции()
  Одобрение_операции()
}
Банкомат <-- Банк: Ответ по поводу операции
Банк <-- Банкомат: Запрос на операцию
Клиент <-- Банкомат: Вывод результата
Банкомат <-- Клиент: Запрос

@enduml
