@startuml ПР1
left to right direction
skinparam packageStyle rect
actor Клиент
actor Банк
rectangle Банкомат {
  Клиент -- (Запрос)
  (Запрос) -> (Проверка счёта): extend
  (Запрос) -> (Снятие наличных со счёта): extend
  (Запрос) -> (Зачисление наличных на счёт): extend
  (Запрос) -> (Оплата различных счетов): extend
  Банк -- (Проверка возможности операции)
  (Проверка возможности операции) -> (Одобрение операции): extend
  (Проверка возможности операции) -> (Отказ в операции): extend
  (Проверка возможности операции) -> (Идентификация банкомата): inulcde
  (Проверка возможности операции) -> (Идентификация счёта): include
  
}


@enduml
